//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RayTracingStd.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FORMVIEW                    102
#define IDD_TEST_DIALOG                 103
#define IDR_MAINFRAME                   104
#define IDR_RAYTRATYPE                  105
#define IDD_FORMULA_DLG                 106
#define IDD_DIALOG1                     107
#define IDD_CAMERA_PAGE                 107
#define IDD_LIGHT_PAGE                  108
#define IDD_FRACTAL_PAGE                109
#define IDD_TEXTURE_GENERAL             110
#define IDD_TEXTURE_PROCEDURAL          111
#define IDC_NULLCURSOR                  129
#define IDS_ERREUR_MSG_1                136
#define IDS_CURRENT_COMPUTING           137
#define IDS_ERROR_FONTFILE              138
#define IDD_EDIT_COLORMAP               141
#define IDR_MENU_COLORMAP               142
#define IDD_IMAGE_PAGE                  142
#define IDD_REGISTER                    143
#define IDR_PRINCIPAL                   143
#define IDD_PREFERENCE                  145
#define IDB_LOGO                        149
#define IDD_LICENCE                     150
#define IDD_SCREENSAVER_PROP            154
#define IDC_FORMULA_EDIT                1000
#define IDC_ROTATE_X                    1002
#define IDC_ROTATE_Y                    1003
#define IDC_ROTATE_Z                    1004
#define IDC_LOOKAT                      1005
#define IDC_POSITION2                   1006
#define IDC_TYPE                        1007
#define IDC_CAMPOSX                     1008
#define IDC_CAMPOSY                     1009
#define IDC_CAMPOSZ                     1010
#define IDC_CAMLOOKX                    1011
#define IDC_CAMLOOKY                    1012
#define IDC_FRACROTZ                    1013
#define IDC_TOP                         1013
#define IDC_CAMTYPE                     1014
#define IDC_NBPROCESSORS                1015
#define IDC_CAMTOPX                     1015
#define IDC_SCREENWIDTH                 1016
#define IDC_BUTTON_RENDER               1017
#define IDC_CAMTOPY                     1017
#define IDC_FOCALE                      1018
#define IDC_LIGHTPOSY                   1019
#define IDC_LIGHTPOSZ                   1020
#define IDC_LIGHTCOLORR                 1021
#define IDC_LIGHTCOLORG                 1022
#define IDC_LIGHTCOLORB                 1023
#define IDC_LIGHTTYPE                   1024
#define IDC_STATICPOS                   1025
#define IDC_STATICPOS2                  1026
#define IDC_FRACTALCSTR                 1027
#define IDC_STATICPOS3                  1030
#define IDC_FRACTALCSTI                 1031
#define IDC_STATICPOS4                  1032
#define IDC_FRACTALCSTJ                 1033
#define IDC_STATICPOS5                  1034
#define IDC_FRACTALCSTK                 1035
#define IDC_FRACTALFORMULA              1036
#define IDC_FRACTALITER                 1037
#define IDC_FRACTALSTEP                 1038
#define IDC_FRACTALDERIVATE             1039
#define IDC_FRACTALTYPE                 1040
#define IDC_FRACTALOPTIM                1041
#define IDC_BUTTON_RANDOM               1042
#define IDC_COLORDIFFUSE                1043
#define IDC_COLORDIFFUSE2               1044
#define IDC_LIGHTCOLOR                  1045
#define IDC_COLORAMBIENT                1046
#define IDC_LIGHTDELETE                 1046
#define IDC_BCOLORDIFFUSE               1047
#define IDC_BCOLORSPEC                  1050
#define IDC_MATIERENAME                 1051
#define IDC_BCOLORAMB                   1052
#define IDC_COLORDIFFUSE3               1053
#define IDC_TEXTDIFFUSE                 1055
#define IDC_COLORMAP                    1056
#define IDC_TEXTAMBIENT                 1057
#define IDC_PROCEDURE                   1058
#define IDC_TEXTSPECULAR                1059
#define IDC_TEXTTRANSPARENT             1060
#define IDC_EDIT_POSITION               1061
#define IDC_COLOR_MAP                   1062
#define IDC_BCOLORTRANS                 1063
#define IDC_FRACTALANGLE                1064
#define IDC_BFRACTALTEXTURE             1065
#define IDC_FRACTALLIMIT                1066
#define IDC_RENDERTYPE                  1067
#define IDC_FRACTALBAILOUT              1067
#define IDC_IMAGEWIDTH                  1068
#define IDC_REGISTER_NAME               1068
#define IDC_IMAGEHEIGHT                 1069
#define IDC_FORMULA_RECORD              1070
#define IDC_FRACPOSX                    1073
#define IDC_FRACPOSY                    1074
#define IDC_FRACPOSZ                    1075
#define IDC_PHONGSIZE                   1077
#define IDC_TEXTURE_SUPPR               1078
#define IDC_FORMULA_DERIVE_EDIT         1079
#define IDC_SCREEN_SAVE                 1081
#define IDC_HYPERLINK                   1082
#define IDC_ED_FOLDER                   1083
#define IDC_DERIVATE_EDIT               1084
#define IDC_ED_FOLDER2                  1085
#define IDC_REGISTER_KEY                1086
#define IDC_ENREGISTRE                  1087
#define IDC_LIGHTADD                    1088
#define IDC_FRACTALTEXTURE              1089
#define IDC_ROTATION                    1090
#define IDC_FRACROTX                    1091
#define IDC_FRACROTY                    1092
#define IDC_CAMLOOKZ                    1093
#define IDC_SCREEN                      1094
#define IDC_LIGHTNAME                   1095
#define IDC_CAMTOPZ                     1095
#define IDC_SCREENHEIGHT                1096
#define IDC_LIGHTPOSX                   1097
#define IDC_FOCALEVALUE                 1098
#define IDS_COLORMAP_COLUMN1            5000
#define IDS_COLORMAP_COLUMN2            5001
#define IDS_COLORMAP_COLUMN3            5002
#define IDS_COLORMAP_COLUMN4            5003
#define IDS_ERROR_PARSINGFILE           5005
#define IDS_TEXTUREPAGE_DIFFUSE         5010
#define IDS_TEXTUREPAGE_AMBIENT         5011
#define IDS_TEXTUREPAGE_SPECULAR        5012
#define IDS_TEXTUREPAGE_TRANSPARENT     5013
#define IDS_REGISTER_OK                 5014
#define IDS_REGISTER_NOK                5015
#define IDS_ERROR_SAVEFILE              5016
#define IDS_COMPUTING_FINISHED          5017
#define IDREGISTER                      5018
#define IDDERIVE                        5019
#define ID_GETFOLDER                    5020
#define IDS_ERROR_NOFRACTAL             5021
#define ID_GETFOLDER2                   5021
#define IDS_NOMBOUTON_RENDER            5022
#define IDS_NOMBOUTON_RANDOM            5023
#define IDS_FRACTAL_TITLE               5024
#define IDS_TEXTURE_TITLE               5025
#define IDS_MOYENNE                     5026
#define IDS_ERROR_FILEINI               5027
#define IDS_RELANCE_APPLI               5028
#define IDS_REGISTER_THANK_OK           5029
#define IDS_REGISTER_ERROR_NOK          5030
#define IDS_RELANCE_APPLI2              5031
#define IDS_RENDU_ANNULE                5032
#define IDS_ERROR_EXPRESSION            5033
#define IDS_ERROR_DERIVEE               5034
#define IDS_ERROR_RENDER                5035
#define IDB_ACCUEIL                     5036
#define IDD_ACCUEIL                     5037
#define IDS_ERROR_SCREENSAVER           5038
#define ID_MENU_FORMULA_EDIT            5039
#define IDS_ERROR_SCREENSAVER2          5039
#define ID_RENDERING_RENDER             5040
#define ID_WINDOW_SHOWHIDEPROPERTIES    5041
#define ID_COLORMAP_INSERTCOLOR         5042
#define ID_COLORMAP_DELETECOLOR         5043
#define ID_COLORMAP_MODIFYCOLOR         5044
#define ID_FICHIER_FERMER               5045
#define ID_FICHIER_ENREGISTRE           5046
#define ID_FICHIER_CHARGE               5047
#define ID_APP_PREFERENCE               5048
#define ID_STOP_RENDER                  5049
#define ID_RENDERING_ALEA               32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
